using Content.Shared.Psionics;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Psionics.Ui;

[GenerateTypedNameReferences]
public sealed partial class PsionicTerminalDisiplineButton : Button
{
    public PsionicTerminalDisiplineButton(ProtoId<PsionicDisiplinePrototype> disiplineId, bool unlocked, IPrototypeManager prototype, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        var disipline = prototype.Index(disiplineId);
        Icon.Texture = sprite.Frame0(unlocked ? disipline.UnlockedIcon : disipline.LockedIcon);
        Name.Text = Loc.GetString(disipline.Name);
        ToolTip = Loc.GetString(disipline.Description);
        Disabled = unlocked;
    }
}
