using Content.Client.UserInterface.Controls;
using Content.Shared.Psionics;
using Content.Shared.Psionics.Ui;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Psionics.Ui;

[GenerateTypedNameReferences]
public sealed partial class PsionicGeneratorSelectorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly SpriteSystem _sprite;

    public Action<ProtoId<PsionicDisiplinePrototype>?>? OnDisiplineSelected;

    private readonly ButtonGroup _disiplineButtonGroup;

    public PsionicGeneratorSelectorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        _disiplineButtonGroup = new(true);
    }

    public void UpdateState(PsionicGeneratorSelectorBoundUserInterfaceState state)
    {
        Grid.RemoveAllChildren();

        Dictionary<ProtoId<PsionicDisiplinePrototype>, PsionicGeneratorSelectorDisiplineButton> buttons = new(state.Disiplines.Count);
        foreach (var disipline in state.Disiplines)
        {
            var button = new PsionicGeneratorSelectorDisiplineButton(disipline, _prototype, _sprite)
            {
                Group = _disiplineButtonGroup
            };
            button.OnToggled += args =>
            {
                if (args.Pressed)
                    OnDisiplineSelected?.Invoke(disipline);
                else
                    OnDisiplineSelected?.Invoke(null);
            };
            buttons[disipline] = button;
            Grid.AddChild(button);
        }

        if (state.CurrentDisipline != null && buttons.TryGetValue(state.CurrentDisipline.Value, out var currentButton))
            currentButton.Pressed = true;
    }
}
