using Content.Client.UserInterface.Controls;
using Content.Shared.Psionics.Ui;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Psionics.Ui;

[GenerateTypedNameReferences]
public sealed partial class PsionicTerminalWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly SpriteSystem _sprite;

    public PsionicTerminalWindow() : base()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();
    }

    public void UpdateState(PsionicTerminalBoundUserInterfaceState state)
    {
        Grid.RemoveAllChildren();
        foreach (var disipline in state.Available)
        {
            var unlocked = state.Unlocked.Contains(disipline);
            var button = new PsionicTerminalDisiplineButton(disipline, unlocked, _prototype, _sprite);
            Grid.AddChild(button);
        }
    }
}
