using Content.Shared.Psionics;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Psionics.Ui;

[GenerateTypedNameReferences]
public sealed partial class PsionicGeneratorSelectorDisiplineButton : ContainerButton
{
    public PsionicGeneratorSelectorDisiplineButton(ProtoId<PsionicDisiplinePrototype> disiplineId, IPrototypeManager prototype, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        var disipline = prototype.Index(disiplineId);
        Icon.Texture = sprite.Frame0(disipline.UnlockedIcon);
        Name.Text = Loc.GetString(disipline.Name);
        ToolTip = Loc.GetString(disipline.Description);
    }
}
